export enum PrescriptionStatus {
  UPLOADED = 'UPLOADED',
  IN_REVIEW = 'IN_REVIEW',
  NEEDS_CLARIFICATION = 'NEEDS_CLARIFICATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  ARCHIVED = 'ARCHIVED'
}